version: '3'

services:
  lonelyfoodie-api:
    container_name: lonelyfoodie-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    working_dir: /app
    volumes:
      - ./:/app/
    networks:
      - lonelyfoodie-api
    depends_on:
      - lonelyfoodie-database

  lonelyfoodie-database:
    container_name: lonelyfoodie-database
    image: postgres:14
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lonelyfoodie
    ports:
      - "5432:5432"
    volumes:
      - lonelyfoodie-pgdata:/var/lib/postgresql/data
    networks:
      - lonelyfoodie-api

networks:
  lonelyfoodie-api:
    driver: bridge

volumes:
  lonelyfoodie-pgdata: