"""fix user table's column

Revision ID: 3b2b7303a095
Revises: c99d6f841121
Create Date: 2021-11-27 04:24:09.931515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b2b7303a095'
down_revision = 'c99d6f841121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'dept_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'student_year',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'])
    op.create_unique_constraint(op.f('uq_users_kakao_id'), 'users', ['kakao_id'])
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_users_kakao_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.alter_column('users', 'sex',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'student_year',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('users', 'dept_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
