"""add review

Revision ID: 53bdb2cf67f6
Revises: 3b2b7303a095
Create Date: 2021-11-30 18:49:11.811914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53bdb2cf67f6'
down_revision = '3b2b7303a095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.String(length=120), nullable=False),
    sa.Column('restaurant_id', sa.String(length=120), nullable=True),
    sa.Column('writer_id', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('content', sa.String(length=120), nullable=False),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_review_restaurant_id_restaurants')),
    sa.ForeignKeyConstraint(['writer_id'], ['users.id'], name=op.f('fk_review_writer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
